obj/ArTerabotArm.o: src/ArTerabotArm.cpp /usr/local/Aria/include/Aria.h \
 /usr/local/Aria/include/ariaOSDef.h \
 /usr/local/Aria/include/ariaTypedefs.h \
 /usr/local/Aria/include/ArSerialConnection.h \
 /usr/local/Aria/include/ArDeviceConnection.h \
 /usr/local/Aria/include/ariaUtil.h /usr/local/Aria/include/ArLog.h \
 /usr/local/Aria/include/ArMutex.h /usr/local/Aria/include/ArFunctor.h \
 /usr/local/Aria/include/ArArgumentParser.h \
 /usr/local/Aria/include/ArArgumentBuilder.h \
 /usr/local/Aria/include/ArBasePacket.h \
 /usr/local/Aria/include/ArTcpConnection.h \
 /usr/local/Aria/include/ArSocket.h \
 /usr/local/Aria/include/ArSimpleConnector.h \
 /usr/local/Aria/include/ArRobotConnector.h \
 /usr/local/Aria/include/ArLaserConnector.h \
 /usr/local/Aria/include/ArLogFileConnection.h \
 /usr/local/Aria/include/ArRobotPacket.h \
 /usr/local/Aria/include/ArRobotPacketSender.h \
 /usr/local/Aria/include/ArRobotPacketReceiver.h \
 /usr/local/Aria/include/ArRobotConfigPacketReader.h \
 /usr/local/Aria/include/ArRobotTypes.h \
 /usr/local/Aria/include/ArRobotParams.h \
 /usr/local/Aria/include/ArConfig.h /usr/local/Aria/include/ArConfigArg.h \
 /usr/local/Aria/include/ArFileParser.h \
 /usr/local/Aria/include/ArHasFileName.h \
 /usr/local/Aria/include/ArConfigGroup.h \
 /usr/local/Aria/include/ArRobot.h /usr/local/Aria/include/ArSyncTask.h \
 /usr/local/Aria/include/ArTaskState.h \
 /usr/local/Aria/include/ArSensorReading.h \
 /usr/local/Aria/include/ArTransform.h \
 /usr/local/Aria/include/ArCondition.h \
 /usr/local/Aria/include/ArSyncLoop.h \
 /usr/local/Aria/include/ArASyncTask.h /usr/local/Aria/include/ArThread.h \
 /usr/local/Aria/include/ArRobotPacketReaderThread.h \
 /usr/local/Aria/include/ArActionDesired.h \
 /usr/local/Aria/include/ArResolver.h \
 /usr/local/Aria/include/ArInterpolation.h \
 /usr/local/Aria/include/ArKeyHandler.h \
 /usr/local/Aria/include/ArCommands.h \
 /usr/local/Aria/include/ArJoyHandler.h \
 /usr/local/Aria/include/ariaInternal.h \
 /usr/local/Aria/include/ArStringInfoGroup.h \
 /usr/local/Aria/include/ArSonarDevice.h \
 /usr/local/Aria/include/ArRangeDevice.h \
 /usr/local/Aria/include/ArRangeBuffer.h \
 /usr/local/Aria/include/ArDrawingData.h \
 /usr/local/Aria/include/ArPriorityResolver.h \
 /usr/local/Aria/include/ArAction.h /usr/local/Aria/include/ArArg.h \
 /usr/local/Aria/include/ArActionGroup.h \
 /usr/local/Aria/include/ArActionGroups.h \
 /usr/local/Aria/include/ArActionColorFollow.h \
 /usr/local/Aria/include/ArACTS.h /usr/local/Aria/include/ArPTZ.h \
 /usr/local/Aria/include/ArPTZConnector.h \
 /usr/local/Aria/include/ArActionDeceleratingLimiter.h \
 /usr/local/Aria/include/ArActionLimiterForwards.h \
 /usr/local/Aria/include/ArActionLimiterBackwards.h \
 /usr/local/Aria/include/ArActionLimiterTableSensor.h \
 /usr/local/Aria/include/ArActionBumpers.h \
 /usr/local/Aria/include/ArActionIRs.h \
 /usr/local/Aria/include/ArActionStallRecover.h \
 /usr/local/Aria/include/ArActionAvoidFront.h \
 /usr/local/Aria/include/ArActionAvoidSide.h \
 /usr/local/Aria/include/ArActionConstantVelocity.h \
 /usr/local/Aria/include/ArActionInput.h \
 /usr/local/Aria/include/ArActionRobotJoydrive.h \
 /usr/local/Aria/include/ArActionJoydrive.h \
 /usr/local/Aria/include/ArActionKeydrive.h \
 /usr/local/Aria/include/ArActionTriangleDriveTo.h \
 /usr/local/Aria/include/ArLineFinder.h \
 /usr/local/Aria/include/ArActionTurn.h \
 /usr/local/Aria/include/ArActionRatioInput.h \
 /usr/local/Aria/include/ArActionStop.h \
 /usr/local/Aria/include/ArActionGoto.h \
 /usr/local/Aria/include/ArModule.h \
 /usr/local/Aria/include/ArModuleLoader.h \
 /usr/local/Aria/include/ArRecurrentTask.h \
 /usr/local/Aria/include/ArGripper.h /usr/local/Aria/include/ArSonyPTZ.h \
 /usr/local/Aria/include/ArRVisionPTZ.h /usr/local/Aria/include/ArAMPTU.h \
 /usr/local/Aria/include/ArP2Arm.h /usr/local/Aria/include/ArSick.h \
 /usr/local/Aria/include/ArLaser.h \
 /usr/local/Aria/include/ArRangeDeviceThreaded.h \
 /usr/local/Aria/include/ArFunctorASyncTask.h \
 /usr/local/Aria/include/ArLMS2xx.h \
 /usr/local/Aria/include/ArLMS2xxPacket.h \
 /usr/local/Aria/include/ArLMS2xxPacketReceiver.h \
 /usr/local/Aria/include/ArLaserLogger.h \
 /usr/local/Aria/include/ArIrrfDevice.h /usr/local/Aria/include/ArDPPTU.h \
 /usr/local/Aria/include/ArVCC4.h /usr/local/Aria/include/ArMode.h \
 /usr/local/Aria/include/ArModes.h \
 /usr/local/Aria/include/ArTCMCompassRobot.h \
 /usr/local/Aria/include/ArTCM2.h /usr/local/Aria/include/ArNetServer.h \
 /usr/local/Aria/include/ArSignalHandler.h \
 /usr/local/Aria/include/ArAnalogGyro.h \
 /usr/local/Aria/include/ArMapInterface.h \
 /usr/local/Aria/include/ArMapObject.h \
 /usr/local/Aria/include/ArMapUtils.h /usr/local/Aria/include/ArMap.h \
 /usr/local/Aria/include/ArMapComponents.h \
 /usr/local/Aria/include/ArBumpers.h /usr/local/Aria/include/ArIRs.h \
 /usr/local/Aria/include/ArForbiddenRangeDevice.h \
 /usr/local/Aria/include/ArVersalogicIO.h \
 /usr/local/Aria/include/ArMTXIO.h \
 /usr/local/Aria/include/ArActionGotoStraight.h \
 /usr/local/Aria/include/ArDataLogger.h \
 /usr/local/Aria/include/ArRobotJoyHandler.h \
 /usr/local/Aria/include/ArRatioInputKeydrive.h \
 /usr/local/Aria/include/ArRatioInputJoydrive.h \
 /usr/local/Aria/include/ArRatioInputRobotJoydrive.h \
 /usr/local/Aria/include/ArActionMovementParameters.h \
 /usr/local/Aria/include/ArSoundPlayer.h \
 /usr/local/Aria/include/ArSoundsQueue.h \
 /usr/local/Aria/include/ArSpeech.h \
 /usr/local/Aria/include/ArCameraCollection.h \
 /usr/local/Aria/include/ArCameraCommands.h \
 /usr/local/Aria/include/ArSonarAutoDisabler.h \
 /usr/local/Aria/include/ArActionDriveDistance.h \
 /usr/local/Aria/include/ArLaserReflectorDevice.h \
 /usr/local/Aria/include/ArRobotConfig.h \
 /usr/local/Aria/include/ArTCMCompassDirect.h \
 /usr/local/Aria/include/ArNMEAParser.h \
 /usr/local/Aria/include/ArLaserFilter.h /usr/local/Aria/include/ArUrg.h \
 /usr/local/Aria/include/ArGPS.h /usr/local/Aria/include/ArTrimbleGPS.h \
 /usr/local/Aria/include/ArNovatelGPS.h \
 /usr/local/Aria/include/ArGPSCoords.h \
 /usr/local/Aria/include/ArSonarConnector.h \
 /usr/local/Aria/include/ArBatteryConnector.h \
 /usr/local/Aria/include/ArLCDConnector.h \
 /usr/local/Aria/include/ArSonarMTX.h \
 /usr/local/Aria/include/ArBatteryMTX.h \
 /usr/local/Aria/include/ArLCDMTX.h \
 /usr/local/Aria/include/ArSimulatedLaser.h \
 /usr/local/Aria/include/ArExitErrorSource.h \
 /usr/local/Aria/include/ArActionLimiterRot.h \
 /usr/local/Aria/include/ArRobotBatteryPacketReader.h \
 /usr/local/Aria/include/ArLMS1XX.h /usr/local/Aria/include/ArUrg_2_0.h \
 /usr/local/Aria/include/ArActionMovementParametersDebugging.h \
 /usr/local/Aria/include/ArZippable.h \
 /usr/local/Aria/include/ArS3Series.h \
 /usr/local/Aria/include/ArSZSeries.h /usr/local/Aria/include/ArExport.h \
 include/ArTerabotArm.h /usr/local/Aria/include/ariaTypedefs.h \
 /usr/local/Aria/include/ariaOSDef.h \
 /usr/local/Aria/include/ArSerialConnection.h \
 /usr/local/Aria/include/ariaUtil.h
