<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> 
  <!-- Import all common definitions -->
  <xacro:include filename="$(find terabot_description)/urdf/common.xacro" />
  <xacro:include filename="$(find terabot_description)/urdf/materials.xacro" />
  <link name="arm_base_link">
    <visual>
      <origin xyz="0 0 ${(80/2)*BASE}" rpy="0 ${-PI/2} ${PI/2}" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
       <geometry>
        <cylinder length="${(229/2)*BASE}" radius="${2*link_radius}"/>
      </geometry>
      <origin xyz="0 0 ${(229/4)*BASE}"/>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="shoulder_joint" type="revolute">
    <origin xyz="0 0 ${(80)*BASE}" rpy="0 0 ${-pi}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${170*(PI/180)}" velocity="0.5"/>
    <parent link="arm_base_link"/>
    <child link="shoulder_link"/>
    <dynamics damping="0.001"/>
  </joint>

  <link name="shoulder_link">
    <visual>
      <origin xyz="0 0 ${-(80/2)*BASE}" rpy="0 ${-pi/2} ${-pi/2}" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/shoulder.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${-(80/2)*BASE}" rpy="0 ${-pi/2} ${pi/2}" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/shoulder.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="forearm_joint" type="revolute">
    <origin xyz="0 0 ${(229/2)*BASE}" rpy="${PI/2} ${-PI/2} ${-PI}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-90*(PI/180)}" upper="${0*(PI/180)}" velocity="0.5"/>
    <parent link="shoulder_link"/>
    <child link="forearm_link"/>
    <dynamics damping="0.001"/>
  </joint>

  <link name="forearm_link">
    <visual>
      <origin xyz="${-(229/2)*BASE+forearm_link_x_offset} ${-(229/2)*BASE+forearm_link_y_offset} 0" rpy="0 0 ${PI/4}" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/forearm.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="${-(229/2)*BASE+forearm_link_x_offset} ${-(229/2)*BASE+forearm_link_y_offset} 0" rpy="0 0 ${PI/4}" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/forearm.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia
	  ixx="0.01" ixy="0.0" ixz="0.0"
	  iyy="0.01" iyz="0.0"
	  izz="0.01"/>
    </inertial>
  </link>

  <joint name="upper_arm_joint" type="revolute">
    <origin xyz="${419.1*BASE} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${162*(PI/180)}" velocity="0.5"/>
    <parent link="forearm_link"/>
    <child link="upper_arm_link"/>
    <dynamics damping="0.007"/>
  </joint>

  <link name="upper_arm_link">
    <visual>
      <origin xyz="${(229/2)*BASE+upper_arm_link_x_offset} ${-419.1*BASE-(229/2)*BASE+upper_arm_link_y_offset} 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/upper_arm.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>


<!--    <collision>
      <geometry>
        <cylinder length="${364.49*BASE}" radius="0.05"/>
      </geometry>
    </collision>-->

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia
	  ixx="0.01" ixy="0.0" ixz="0.0"
	  iyy="0.01" iyz="0.0"
	  izz="0.01"/>
    </inertial>
  </link>

  <joint name="wrist_pitch_joint" type="revolute">
    <origin xyz="${364.49*BASE} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${170*(PI/180)}" velocity="0.5"/>
    <parent link="upper_arm_link"/>
    <child link="wrist_pitch_link"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="wrist_pitch_link">
    <visual>
      <origin xyz="${(364.49/2)*BASE+wrist_pitch_link_x_offset} ${-419.1*BASE-(229/2)*BASE+wrist_pitch_link_y_offset} 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/wrist_pitch.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

     <visual>
      <origin xyz="${(-100.49/2)*BASE+wrist_pitch_link_x_offset} ${230.1*BASE-(229/2)*BASE+wrist_pitch_link_y_offset} 0" rpy="0 ${PI/2} 0" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/arm_camera.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

<!--    <collision>
      <geometry>
        <cylinder length="${364.49*BASE}" radius="0.05"/>
      </geometry>
    </collision>-->

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

 <!-- added end effector for calibration -->
  
 <joint name="end_effector_joint" type="fixed">
      <origin xyz="0.09 ${wrist_roll_joint_z_offset} 0" rpy="0 0 0"/>    <!-- before modifications -->
<!--   <origin xyz="0.09 0.04 0.006" rpy="0 0 0"/> --><!-- original is 0.085 but we have the torque sensor...-->

      <axis xyz="0 0 1"/>
      <parent link="wrist_pitch_link"/>
      <child link="end_effector"/>
      <dynamics damping="100.0" friction="100.0" />
      </joint>
      <!-- end_effector -->
      <link name="end_effector">
	<origin xyz="0 0 0" rpy="0 0 0"/>
      <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
      ixx="1.0" ixy="0.0" ixz="0.0"
      iyy="1.0" iyz="0.0"
      izz="1.0"/>
      </inertial>
      </link>
  
 <!-- modified the following part to add end_effector link (marker) for calibration -->

 <joint name="wrist_roll_joint" type="revolute">
   <!-- origin xyz="${50*BASE+0.013+wrist_roll_joint_x_offset} ${wrist_roll_joint_z_offset} 0" rpy="0 ${PI/2} 0"/ --> <!-- when the parent is wrist pitch joint -->
        <origin xyz="0.07 0 0" rpy="0 ${PI/2} 0"/><!-- when the end effector is the parent -->
  <!--   <origin xyz="0.07 -0.005 0" rpy="0 ${PI/2} 0"/>-->
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${170*(PI/180)}" velocity="0.5"/>
    <parent link="end_effector"/>
    <child link="wrist_roll_link"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="wrist_roll_link">
    <visual>
<!--      <origin xyz="-0.0322 ${0.4*BASE+wrist_roll_link_y_offset} ${-18.5*BASE+wrist_roll_link_x_offset}" rpy="0 -${PI} ${3*PI/2}" />--><!-- when the parent is wrist pitch joint -->
<origin xyz="-0.0322 ${0.4*BASE+wrist_roll_link_y_offset} ${-18.5*BASE+wrist_roll_link_x_offset}" rpy="0 -${PI} ${3*PI/2}" /><!-- when the end effector is the parent -->
<!--     <origin xyz="-0.0315 0 ${-18.5*BASE+wrist_roll_link_x_offset}" rpy="0 -${PI} ${3*PI/2}" />    -->
      <geometry>
        <mesh filename="package://terabot_description/meshes/wrist_roll.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
ixx="1.0" ixy="0.0" ixz="0.0"
iyy="1.0" iyz="0.0"
izz="1.0"/>
    </inertial>
  </link>

  <joint name="gripper_l_finger_joint" type="revolute">
    <origin xyz="${gripper_l_finger_joint_x_offset} 0 -0.0145" rpy="0 ${3*PI/2} ${3*PI/2}"/>
    <limit effort="1000.0" lower="0.0" upper="${40*(PI/180)}" velocity="0.5"/>
    <axis xyz="0 0 -1"/>

    <parent link="wrist_roll_link"/>
    <child link="gripper_l_finger_link"/>
  </joint>

  <link name="gripper_l_finger_link">
    <visual>
      <origin xyz="0 0 0" rpy="-${3*PI/2.35} -${PI/2} ${3*PI/2}" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/left_finger.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="brown"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

   <joint name="gripper_r_finger_joint" type="revolute">
    <origin xyz="${gripper_r_finger_joint_x_offset} 0 -0.0145" rpy="0 ${3*PI/2} ${3*PI/2}"/>
    <limit effort="1000.0" lower="0.0" upper="${40*(PI/180)}" velocity="0.5"/>
    <axis xyz="0 0 1"/>
    <mimic joint="gripper_l_finger_joint"/>
    <parent link="wrist_roll_link"/>
    <child link="gripper_r_finger_link"/>
  </joint>

  <link name="gripper_r_finger_link">
    <visual>
      <origin xyz="-0.0355 -0.0415 0" rpy="-${3*PI/1.74} -${PI/2} ${3*PI/2}" />
      <geometry>
        <mesh filename="package://terabot_description/meshes/right_finger.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="brown"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>



  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="forearm_joint">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="upper_arm_joint">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>    
    <actuator name="motor3">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_pitch_joint">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>        
    <actuator name="motor4">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_roll_joint">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>        
    <actuator name="motor5">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran6">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gripper_r_finger_joint">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>        
      <actuator name="motor6">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

  <transmission name="tran7">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gripper_l_finger_joint">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>        
      <actuator name="motor7">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>  
  

</robot>