terabot_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  shoulder_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  forearm_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: forearm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  upper_arm_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: upper_arm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0} 
  wrist_pitch_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_roll_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
#   gripper_l_finger_joint_position_controller:
#     type: position_controllers/JointPositionController
#     joint: gripper_l_finger_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}
#   gripper_r_finger_joint_position_controller:
#     type: position_controllers/JointPositionController
#     joint: gripper_r_finger_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}

    
       
  # Trajectory Controllers ---------------------------------------
  terabot_arm_trajectory_controller:
    type: position_controllers/JointTrajectoryController
#    type: effort_controllers/JointTrajectoryController
    joints:
      - shoulder_joint
      - forearm_joint
      - upper_arm_joint
      - wrist_pitch_joint
      - wrist_roll_joint
#       - gripper_l_finger_joint
#       - gripper_r_finger_joint
      
    state_publish_rate: 20.0
    action_monitor_rate: 20.0
    constraints:
      goal_time: 100.0                   # Override default
      shoulder_joint:
        trajectory: -1.0
      forearm_joint:
        trajectory: -1.0
      upper_arm_joint:
        trajectory: -1.0
      wrist_pitch_joint:
        trajectory: -1.0
      wrist_roll_joint:
        trajectory: -1.0
#       gripper_l_finger_joint:
#         trajectory: -1.0
#       gripper_r_finger_joint:
#         trajectory: -1.0
      
