controller_list:
 - name: /terabot_arm/terabot_arm_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - shoulder_joint
     - forearm_joint
     - upper_arm_joint
     - wrist_pitch_joint
     - wrist_roll_joint
     - gripper_l_finger_joint
#      - gripper_r_finger_joint

